---
title: purple cedar
baseURL: "/"
params:
  layout_style: grid
  palette: green
  header:
    title: Purple Cedar
    logo_img: images/logo.png
    has_nav: true
  footer:
    content: "&copy; All rights reserved."
    links:
    - text: 'made by #esc'
      url: https://eaglesoftware.tech
      new_window: true
    has_social: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
